version: "3"
services:
  # Microservice 1 (Bash Script Service with FastAPI)
  sms_system:
    build: ./backend/sms_system
    container_name: sms_system
    restart: always
    command: >
      /bin/sh -c "uvicorn main:app --host 0.0.0.0 --port 8001"
    # volumes:
    #   - ./app:/app
    links:
      - mongo
    ports:
      - "8001:8001" # Expose API for Microservice 1 on port 8001
    depends_on:
      - mongo
  management_server:
    container_name: management_server
    build: ./backend
    # dockerfile: Dockerfile
    command: >
      /bin/sh -c "alembic upgrade head &&
      echo \"Starting Management Server\" &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - relational_db
      - mongo
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=relational_db
      - MONGO_HOST=mongo
      - SMS_HOST=sms_system
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
  web_server:
    build: ./frontend
    container_name: web_server
    restart: always
    command: >
      /bin/sh -c "npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173" # Expose API for Microservice 1 on port 8001
    depends_on:
      - management_server
    environment:
      - VITE_APP_BASE_URL=http://localhost:8000/api
  relational_db:
    image: postgres:15.2-alpine
    restart: always
    # POSTGRES_USER and POSTGRES_PASSWORD should be set in .env file
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  db_volume:
  mongo_volume:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data
