{
 "title": "sms manament",
 "description": "dashboard for sms management for sent recived success rate and all",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sms Attempt",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_attempts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sms sent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sms confirmed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_confirmed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sms success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_confirm_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sms confired rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sms_confirm_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process Cpu second ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}